services:
  nextjs-frontend:
    build: frontend
    container_name: nextjs-frontend
    stdin_open: true
    tty: true

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-polls}
      POSTGRES_USER: ${DATABASE_USERNAME:-myuser}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-mypassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  django-backend:
    build: ./backend
    container_name: django-backend
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DATABASE_NAME: ${DATABASE_NAME:-polls}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-myuser}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-mypassword}
      DATABASE_HOST: ${DATABASE_HOST:-db}
      DATABASE_PORT: ${DATABASE_PORT:-5432}

volumes:
  postgres_data:
