# Generated by Django 5.2 on 2025-08-04 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublisherMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default='member', max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='publishers.publisher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_memberships', to='users.user')),
            ],
            options={
                'verbose_name': 'Publisher Membership',
                'verbose_name_plural': 'Publisher Memberships',
                'unique_together': {('user', 'publisher')},
            },
        ),
        migrations.AddField(
            model_name='publisher',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='publishers', through='publishers.PublisherMembership', to='users.user'),
        ),
    ]
