# Generated by Django 5.2.5 on 2025-09-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0002_publisher_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='join_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
