# Generated by Django 5.2.5 on 2025-12-07 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0004_publisher_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
