# Generated by Django 5.2.5 on 2025-09-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='join_code',
            field=models.TextField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
