# Generated by Django 5.2.5 on 2025-10-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0003_alter_publisher_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
