# Generated by Django 5.2.5 on 2025-12-26 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0005_publisher_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('join_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='publishermembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='members',
        ),
        migrations.RemoveField(
            model_name='publishermembership',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='publishermembership',
            name='user',
        ),
        migrations.CreateModel(
            name='MagazineMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default='member', max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='magazines.magazine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazine_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Magazine Membership',
                'verbose_name_plural': 'Magazine Memberships',
            },
        ),
        migrations.AddField(
            model_name='magazine',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='magazines', through='magazines.MagazineMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
