# Generated by Django 5.2.5 on 2025-12-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0006_magazine_remove_publisher_members_and_more'),
        ('papers', '0017_remove_raportreview_raport_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='PublisherMembership',
        ),
        migrations.AlterUniqueTogether(
            name='magazinemembership',
            unique_together={('user', 'magazine')},
        ),
    ]
