# Generated by Django 5.2.5 on 2026-01-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0007_delete_publisher_delete_publishermembership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazinemembership',
            name='role',
        ),
    ]
