import './polyfills';
import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Roboto, Poppins } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import "./globals.css";


import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { UserProvider } from "./context/UserContext";
import { UIProvider } from "./context/UIContext";
import { InterceptorSetup } from '@/app/components/InterceptorSetup';
import { cookies } from "next/headers";
import jwt from 'jsonwebtoken';
config.autoAddCss = false

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies();
  const accessToken = cookieStore.get('accessToken')?.value;

  let isStaff = false;

  if (accessToken) {
    try {
      const decoded = jwt.decode(accessToken);

      if (typeof decoded === 'object' && decoded !== null && 'is_staff' in decoded) {
        isStaff = Boolean(decoded.is_staff);
        console.log('isStaff: ', isStaff)
      }
    } catch (e) {
      console.error("Token parse error", e);
    }
  }

  return (
    <html lang="en" className={poppins.variable}>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <UIProvider>
              <UserProvider initialIsStaff={isStaff} initialIsAuthenticated={!!accessToken}>
                <InterceptorSetup />
                {children}
              </UserProvider>
            </UIProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
