# Generated by Django 5.2 on 2025-08-04 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('magazines', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('pending', 'Pending'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('raport_type', models.CharField(choices=[('original_research', 'Artykuł oryginalny'), ('review_article', 'Artykuł przeglądowy'), ('systematic_review', 'Przegląd systematyczny'), ('meta_analysis', 'Metaanaliza'), ('case_report', 'Raport przypadku / Studium przypadku'), ('short_communication', 'Krótki komunikat / Krótki raport'), ('method_article', 'Artykuł metodologiczny'), ('commentary', 'Komentarz / Opinia / List do redakcji'), ('theoretical_paper', 'Artykuł teoretyczny'), ('clinical_trial_report', 'Raport z badania klinicznego'), ('software_tool_article', 'Artykuł oprogramowania'), ('technical_report', 'Raport techniczny'), ('other', 'Inny')], default='original_research', max_length=30)),
                ('category', models.CharField(choices=[('artificial_intelligence', 'Sztuczna Inteligencja (AI)'), ('machine_learning', 'Uczenie Maszynowe (ML)'), ('data_science', 'Data Science / Analiza Danych'), ('cybersecurity', 'Cyberbezpieczeństwo'), ('cloud_computing', 'Przetwarzanie w Chmurze (Cloud Computing)'), ('web_development', 'Tworzenie Aplikacji Webowych'), ('mobile_development', 'Tworzenie Aplikacji Mobilnych'), ('game_development', 'Tworzenie Gier'), ('devops', 'DevOps'), ('networking', 'Sieci Komputerowe'), ('databases', 'Bazy Danych'), ('operating_systems', 'Systemy Operacyjne'), ('software_engineering', 'Inżynieria Oprogramowania'), ('computer_graphics', 'Grafika Komputerowa'), ('robotics', 'Robotyka'), ('internet_of_things', 'Internet Rzeczy (IoT)'), ('blockchain', 'Blockchain / Kryptowaluty'), ('quantum_computing', 'Obliczenia Kwantowe'), ('human_computer_interaction', 'Interakcja Człowiek-Komputer (HCI)'), ('other', 'Inne')], default='artificial_intelligence', max_length=30)),
                ('abstract', models.TextField()),
                ('file', models.FileField(upload_to='papers/files/')),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_papers', to='users.user')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='magazines.publisher')),
            ],
            options={
                'verbose_name': 'Raport',
                'verbose_name_plural': 'Raports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RaportReviewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('raport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raport_reviews', to='papers.raport')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='users.user')),
            ],
            options={
                'verbose_name': 'Raport Reviewer',
                'verbose_name_plural': 'Raport Reviewers',
                'unique_together': {('raport', 'reviewer')},
            },
        ),
        migrations.AddField(
            model_name='raport',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='reviewed_papers', through='papers.RaportReviewers', to='users.user'),
        ),
    ]
