# Generated by Django 5.2.5 on 2025-09-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_rename_comments_raportreview_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='raportreview',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
