# Generated by Django 5.2.5 on 2025-11-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_alter_raport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raportreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('submitted', 'Submitted Review'), ('invited', 'Reviewer Invited'), ('invite_rejected', 'Invite rejected')], default='invited', max_length=20),
        ),
    ]
