# Generated by Django 5.2.5 on 2025-12-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0011_alter_raportreview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raportreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('submitted', 'Submitted Review'), ('approved', 'Approved'), ('invited', 'Reviewer Invited'), ('invite_rejected', 'Invite rejected')], default='invited', max_length=20),
        ),
    ]
