# Generated by Django 5.2.5 on 2025-12-26 19:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0006_magazine_remove_publisher_members_and_more'),
        ('papers', '0016_appsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raportreview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='raportreview',
            name='raport',
        ),
        migrations.RemoveField(
            model_name='raportreview',
            name='reviewer',
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('waiting_for_revision', 'Waiting for Revision')], default='pending', max_length=20)),
                ('paper_type', models.CharField(choices=[('original_research', 'Artykuł oryginalny'), ('review_article', 'Artykuł przeglądowy'), ('systematic_review', 'Przegląd systematyczny'), ('meta_analysis', 'Metaanaliza'), ('case_report', 'Raport przypadku / Studium przypadku'), ('short_communication', 'Krótki komunikat / Krótki raport'), ('method_article', 'Artykuł metodologiczny'), ('commentary', 'Komentarz / Opinia / List do redakcji'), ('theoretical_paper', 'Artykuł teoretyczny'), ('clinical_trial_report', 'Raport z badania klinicznego'), ('software_tool_article', 'Artykuł oprogramowania'), ('technical_report', 'Raport techniczny'), ('other', 'Inny')], default='original_research', max_length=30)),
                ('category', models.CharField(choices=[('artificial_intelligence', 'Sztuczna Inteligencja (AI)'), ('machine_learning', 'Uczenie Maszynowe (ML)'), ('data_science', 'Data Science / Analiza Danych'), ('cybersecurity', 'Cyberbezpieczeństwo'), ('cloud_computing', 'Przetwarzanie w Chmurze (Cloud Computing)'), ('web_development', 'Tworzenie Aplikacji Webowych'), ('mobile_development', 'Tworzenie Aplikacji Mobilnych'), ('game_development', 'Tworzenie Gier'), ('devops', 'DevOps'), ('networking', 'Sieci Komputerowe'), ('databases', 'Bazy Danych'), ('operating_systems', 'Systemy Operacyjne'), ('software_engineering', 'Inżynieria Oprogramowania'), ('computer_graphics', 'Grafika Komputerowa'), ('robotics', 'Robotyka'), ('internet_of_things', 'Internet Rzeczy (IoT)'), ('blockchain', 'Blockchain / Kryptowaluty'), ('quantum_computing', 'Obliczenia Kwantowe'), ('human_computer_interaction', 'Interakcja Człowiek-Komputer (HCI)'), ('other', 'Inne')], default='artificial_intelligence', max_length=30)),
                ('abstract', models.TextField()),
                ('file', models.FileField(upload_to='papers/files/')),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_papers', to=settings.AUTH_USER_MODEL)),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='magazines.magazine')),
            ],
            options={
                'verbose_name': 'Paper',
                'verbose_name_plural': 'Papers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('grade', models.FloatField(blank=True, help_text='Grade from 0 to 5', null=True)),
                ('custom_grade', models.FloatField(blank=True, help_text='Admin defined grade', null=True)),
                ('content_consistency', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('goal_formulation', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('structure_correctness', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('terminology_relevance', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('graphic_design', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('aesthetics', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('literature_selection', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('conclusions_correctness', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('goal_achievement', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('language_correctness', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('submitted', 'Submitted Review'), ('approved', 'Approved'), ('invited', 'Reviewer Invited'), ('invite_rejected', 'Invite rejected')], default='invited', max_length=20)),
                ('decision', models.CharField(blank=True, choices=[('accept', 'Accept'), ('minor_revision', 'Minor Revision'), ('major_revision', 'Major Revision'), ('reject', 'Reject')], max_length=20, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='papers.paper')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paper Review',
                'verbose_name_plural': 'Paper Reviews',
                'unique_together': {('paper', 'reviewer')},
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='reviewed_papers', through='papers.PaperReview', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Raport',
        ),
        migrations.DeleteModel(
            name='RaportReview',
        ),
    ]
