# Generated by Django 5.2.5 on 2026-01-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0017_remove_raportreview_raport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(upload_to='papers/'),
        ),
    ]
