# Generated by Django 5.2 on 2025-08-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raports', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaportReviewers',
            new_name='RaportReview',
        ),
        migrations.AlterModelOptions(
            name='raportreview',
            options={'verbose_name': 'Raport Review', 'verbose_name_plural': 'Raport Reviews'},
        ),
    ]
