# Generated by Django 5.2 on 2025-08-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raports', '0002_rename_raportreviewers_raportreview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raportreview',
            old_name='comments',
            new_name='comment',
        ),
    ]
