# Generated by Django 5.2.5 on 2025-10-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raports', '0004_raportreview_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raportreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('submitted', 'Submitted Review')], default='pending', max_length=10),
        ),
    ]
