# Generated by Django 5.2.5 on 2025-10-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raports', '0005_alter_raportreview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raportreview',
            name='grade',
            field=models.FloatField(blank=True, help_text='Grade from 0 to 5', null=True),
        ),
    ]
