# Generated by Django 5.2.5 on 2025-11-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raports', '0006_alter_raportreview_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raport',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('pending', 'Pending'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='sent', max_length=10),
        ),
    ]
