# Generated by Django 5.2.5 on 2025-12-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raports', '0010_alter_raportreview_aesthetics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raportreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('submitted', 'Submitted Review'), ('approved', 'Approved'), ('rejected_by_admin', 'Rejected by Admin'), ('invited', 'Reviewer Invited'), ('invite_rejected', 'Invite rejected')], default='invited', max_length=20),
        ),
    ]
