# Generated by Django 5.2.5 on 2025-12-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raports', '0012_alter_raportreview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='raportreview',
            name='decision',
            field=models.CharField(blank=True, choices=[('accept', 'Accept'), ('minor_revision', 'Minor Revision'), ('major_revision', 'Major Revision'), ('reject', 'Reject')], max_length=20, null=True),
        ),
    ]
