# Generated by Django 5.2.5 on 2025-12-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raports', '0013_raportreview_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raport',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('pending', 'Pending'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('waiting_for_revision', 'Waiting for Revision')], default='sent', max_length=20),
        ),
    ]
