# Generated by Django 5.2.5 on 2025-12-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raports', '0014_alter_raport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='raportreview',
            name='custom_grade',
            field=models.FloatField(blank=True, help_text='Admin defined grade', null=True),
        ),
        migrations.AlterField(
            model_name='raport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('waiting_for_revision', 'Waiting for Revision')], default='pending', max_length=20),
        ),
    ]
