# Generated by Django 5.2.5 on 2025-12-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raports', '0015_raportreview_custom_grade_alter_raport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract_min_words', models.IntegerField(default=150)),
                ('abstract_max_words', models.IntegerField(default=250)),
                ('review_min_words', models.IntegerField(default=50)),
                ('review_max_words', models.IntegerField(default=500)),
            ],
            options={
                'verbose_name': 'Application Settings',
                'verbose_name_plural': 'Application Settings',
            },
        ),
    ]
